### ISSUE TITLE
Same colour CB

### ISSUE THREAD

**Issue by mellester** [TheDivexz/excelmakesbelhappypack#28]

**Comment by stackpoint** [comment]
I may be having some minor performance issues. Not definitive though. 

I would like to refine the wargoal type though. Border dispute is good but I would definitely like to add options for the AI to return cores and release nations since those also cause nations to shrink with causing as much AE.

Also, I did notice "# NOTE: The order in which the peace options are listed is the order in which the AI will normally prioritize them in peace treaties" in the files. This could help us encourage the AI to take more vassals in peace deals.
