### ISSUE TITLE
Flavor Text Changes

### ISSUE THREAD

**Issue by stackpoint** [TheDivexz/excelmakesbelhappypack#51]
Constant changes in the mod's functional code, creates a mismatch between code and flavor text. For example - Idea 'Corvettes' had its function changed from `ship_durability` to `recover_army_morale` but the in game description still referred to the navy.

These are identified issues can be worked on to make the user experience more pleasant :)

**Current Issues:**
NULL

**CANNOT REPLICATE**
 "Also, we had localization issues with elective monarchy event names/effects showing up as bonus_id_3, for example"

**Comment by Grociu** [comment]
Ideas possibly affected by this are listed below. These vanilla ideas had their effect changed by more than a numbers tweak. For each of these the name of variable stayed the same and no new text was provided. Some can be left as is I think. 

`scientific_revolution`
MOD:  reform_progress_growth = 0.33	innovativeness_gain = 0.15
Vanilla: technology_cost = -0.1 embracement_cost = -0.1
`scientific_revolution_desc:0 "We should strive towards a social and economic revolution marked by technological inventions and a transfer from an agricultural society into an industrial one."`

`efficient_spies `
MOD: spy_offence = 0.5	can_fabricate_for_vassals = yes
Vanilla: spy_offence = 0.5 advisor_cost = -0.10
`efficient_spies_desc:0 "Most peasants will sell their own mother for cash but find those who can do something truly useful is more difficult. Through experience we are learning to separate the wheat from the chaff."`

`agent_training`
MOD: discipline = 0.025
Vanilla: diplomats = 1
`agent_training_desc:0 "We have many covert operations planned but lack the men for the tasks. Establishing a training method for our spies will help bolster the available agents for dangerous missions."`

`military_drill`
MOD: land_morale = 0.10 recover_army_morale_speed = 0.05
Vanilla: land_morale = 0.15
` military_drill_desc:0 "Allows us to invest in military training and thereby improve battle formations, weapon handling and boost the morale of our army."
`

`regimental_system`
MOD: fire_damage_received = -0.05
Vanilla: land_maintenance_modifier = -0.05
`regimental_system_desc:0 "By organizing our armies into regiments tied to distinct geographical areas we can allow the army to put down roots into the community. Thus when we come to raise more battalions for our regiments they will be able to be recruited faster."`

`defensive_mentality`
MOD: shock_damage_received = -0.05 defensiveness = 0.1
Vanilla: fort_maintenance_modifier = -0.1 defensiveness = 0.2
`defensive_mentality_desc:0 "There are those who think that attack is the best form of defense, but that is foolish let them come to us and then hit them on the counter. Our troops will defend tenaciously and our fortresses will hold out for longer."`

`improved_foraging`
MOD: land_maintenance_modifier = -0.10
Vanilla: land_attrition = -0.25
` improved_foraging_desc:0 "Traditionally we were unable to fight effectively in lands which did not supply a lot of food. However our troops have become better at acquiring food allowing larger armies to fight."`

`merchant_adventures`
MOD: global_prov_trade_power_modifier = 0.2
Vanilla: trade_range_modifier = 0.25
`merchant_adventures_desc:0 "Allows us to make use of the numerous traders lusting for fame and fortune, eager to offer their services for a chance to search and explore new trade routes."`

`organised_construction`
MOD: build_cost = -0.1 build_time = -0.25
Vanilla: build_cost = -0.1
`organised_construction_desc:0 "The need to upgrade the infrastructure of our government is a costly business, if we structure the process correctly we can do this cheaper."`

`vice_roys`
MOD: global_tariffs = 0.20
Vanilla: global_tariffs = 0.10 envoy_travel_time = -0.20
`vice_roys_desc:0 "Makes it possible for us to establish Viceroys and thereby improve the administration of our Colonies and increase the amount of money they generate."`

`free_colonies`
MOD: colonists = 1	expel_minorities_cost = -0.25
Vanilla: expel_minorities_cost = -0.25
`free_colonies_desc:0 "Only so many people are willing to move abroad to expand our great colonial empire. However the promise of a plot of land to farm, in free hold, will encourage many more people to seek their fortune abroad. The nice thing about it is that there is plenty of land for everyone."`

`sea_hawks`
MOD: navy_tradition = 1
Vanilla: free_leader_pool = 1 admiral_cost = -0.25
`sea_hawks_desc:0 "Allows us to focus heavily on military advancements and thereby increase our naval tradition."`

`naval_fighting_instruction`
MOD: leader_naval_fire = 1
Vanilla: blockade_efficiency = 0.5 privateer_efficiency = 0.25
`naval_fighting_instruction_desc:0 "Allows our naval veterans to devise new methods to improve our fleet's efficiency in blockades."`

`private_to_marshal`
MOD: cavalry_fire = 0.05	cavalry_shock = 0.1
Vanilla: infantry_power = 0.1
`private_to_marshal_desc:0 "Every private has a marshal's baton in his back. Well, perhaps not exactly, but for those who distinguish themselves in battle, promotion and rewards will follow. The troops know this and are inspired by it."`

`quality_education`
MOD: land_morale = 0.05
Vanilla: army_tradition = 1
` quality_education_desc:0 "The most vital moment of any army's existence is straight after a battle. Win or lose, exhausted troops are most vulnerable. We must ensure that our troops are ready for combat before the opposition is."`

`finest_of_horses`
MOD: infantry_shock = 0.1
Vanilla: cavalry_power = 0.1
`finest_of_horses:0 "Finest of Horses"`
`finest_of_horses_desc:0 "How steadily those troops take the ground! How beautifully those cavalry form! Look at those grey horses! Who are those fine horsemen? These are fine troops."`

`escort_ships`
MOD: recover_army_morale_speed = 0.33
Vanilla: ship_durability = 0.05
`escort_ships:0 "Corvettes"`
`escort_ships_desc:0 "Corvettes were a class of small warships that were designed to escort friendly vessels and harrass the enemy, relying on speed and maneuverability rather than massed firepower."`

`naval_drill`
MOD: yearly_army_professionalism = 0.005
Vanilla: naval_morale = 0.10
`naval_drill:0 "Naval Drill"`
`naval_drill_desc:0 "The confusion of combat can leave a warship unfit for action for a long time. A well drilled crew will recover much faster than an ordinary one."`

`copper_bottoms`
MOD: infantry_fire = 0.1
Vanilla: naval_attrition = -0.25
`copper_bottoms:0 "Copper Bottoms"`
`copper_bottoms_desc:0 "Wood may be the ideal material for shipbuilding, but it has a tendency to deteriorate over time. By fitting our ships with copper sheathing below the waterline we can reduce this deterioration, allowing them to better withstand long journeys."`

`massed_battery`
MOD: artillery_fire = 0.1	artillery_shock = 0.05
Vanilla: artillery_power = 0.1
`massed_battery_desc:0 "Let us mass our artillery in a single grand battery, its destructive power will blast a hole in the enemy lines."`

`mass_army`
MOD: naval_forcelimit = 20 land_forcelimit = 20
Vanilla: global_manpower_modifier = 0.50
`mass_army:0 "Levée en Masse"`
`mass_army_desc:0 "We have, up to now, been very choosy over who should serve as a ranker in our military. We only took the poorest and most desperate, basically the people no one else would miss. Now though we are going to open up the ranks to everyone, who isn't rich."`

`enforced_service`
MOD: land_forcelimit_modifier  = 0.50
Vanilla: global_regiment_cost = -0.1
`enforced_service:0 "Enforced Service"`
`enforced_service_desc:0 "The principle of volunteering underpins our whole army structure. Sometimes there aren't enough volunteers. We should force people to volunteer."`

`mercenary_contracts`
MOD: reinforce_cost_modifier = -0.30
Vanilla: this is not used in the vanilla ideas atm, but has a localisation. Obsolete idea?
`mercenary_contracts:0 "Mercenary Contracts"`
 `mercenary_contracts_desc:0 "By drawing up standing contracts with certain mercenary captains we can ensure that we will always have access to a large pool of mercenaries to draw on, should they be needed."`

`expanded_supply_trains `
MOD: global_supply_limit_modifier = 0.30
Vanilla: land_attrition = -0.1
`expanded_supply_trains:0 "Expanded Supply Trains"`
` expanded_supply_trains_desc:0 "Investing more resources into our supply trains will allow our army to operate for longer periods of time in hostile land."`

`organised_recruiting`
MOD: colonists = 1
Vanilla:  this is not used in the vanilla ideas atm, but has a localisation. Obsolete idea?
` organised_recruiting:0 "Organized Recruitment"`
` organised_recruiting_desc:0 "In days of yore when a captain sought to recruit men to fill his regiment, the process was time-consuming as not many people wished to embrace certain death in our armies. However, by applying the principles of reason to this problem we will be able to come up with a system that will get men into uniform much quicker."`

`tribute_system`
MOD: trade_efficiency = 0.1
Vanilla: vassal_income = 0.25
`tribute_system:0 "Tribute System"`
`tribute_system_desc:0 "Strengthen our income by establishing a formalized system of yearly tribute from our vassals."`

`integrated_elites`
MOD: yearly_absolutism = 1.0	diplomatic_annexation_cost = -0.15
Vanilla: diplomatic_annexation_cost = -0.25
` integrated_elites:0 "Integrated Elites"`
` integrated_elites_desc:0 "By bringing the ruling elite of our subject nations into our government we can smoothen the process of integrating their provinces significantly."`

`postal_service`
MOD: diplomatic_upkeep = 2
Vanilla: envoy_travel_time = -0.25
` postal_service:0 "Postal Service"`
` postal_service_desc:0 "With communications being what they are, it is difficult to ensure that our diplomatic dispatches arrive in a timely fashion. Creating a network of post offices and courier rest stops will make it easier for our voice to be heard in distant lands."`

`marcher_lords`
MOD: land_forcelimit_modifier = 0.15
Vanilla: vassal_forcelimit_bonus = 1
` marcher_lords:0 "Marcher Lords"`
` marcher_lords_desc:0 "By granting considerable autonomy to vassals in border regions, these 'Marcher Lords' will be able to raise large military armies to support us in our wars."`

**Comment by stackpoint** [comment]
If the idea groups are going to be changed soon than it's probably not necessary to update the flavor text at the moment.

**Comment by Grociu** [comment]
* [ ] Make a reflavor pass on the Fleet Base idea group.
* [ ] Nobility Estate click was changed to no longer give manpower, requires the Monarchy Idea finisher, both need new flavor.
