### ISSUE TITLE
Give extra relation for only military access

### ISSUE THREAD

**Issue by mellester** [TheDivexz/excelmakesbelhappypack#7]
A triggered modifier for every player nation that adds a +1 relations for nations with only  Mill acces relations.

**Comment by dhruv-tailor** [comment]
do you think it'd be possible to get rid of mil access taking a relationship slot rather than adding +/- 1 relation every time cause that is open for abuse as well. say you're at 4/4 relations then ask for mil access. you now have 5/5 you can now abuse it and get into an alliance and royal marriage with them for free now

**Comment by mellester** [comment]
it needs to stop giving you that free dip relations the moment you gain a royal mariieg

**Comment by stackpoint** [comment]
I can't find anything in the code that references the types of diplomatic relations a country has.

**Comment by mellester** [comment]
You will have to check if there alied or have subject rrealtions etc

**Comment by stackpoint** [comment]
According to: https://eu4.paradoxwikis.com/Diplomacy#Diplomatic_relations_cap 

- Alliances: alliance_with
- Royal marriages: has_opinion_modifier
- Guarantees: guaranteed_by
- Having a vassal or junior personal union partner: <subject_type>
- Receiving military access
- Supporting independence
- Having a client state: <subject_type>

I just realized that there's a way to check the mil access using has_opinion_modifier since there is an opinion modifier.

**Comment by mellester** [comment]
Also you check the number of used relations a player has and check that gainst they other list

**Comment by mellester** [comment]
```Lua
every_country = {
	limit ={
	ROOT = {
		has_opinion_modifier = {
		who = PREV
		modifier = opinion_military_access
	} 	} 	}
	log = "has op mod mil opinion_military_access [This.GetName]"
}```

this doesntwork
it works for `modifier = scornfully_insulted ` but not opinion_military_access
